### ISSUE TITLE
Add 'output' directory inside fortran dir

### ISSUE THREAD

**Issue by s1291** [dorchard/navier#2]
the code compiles fine but the execution fails because there is no output/00000.ppm so you need to add manually that folder.
Because Git does not cannot track empty folders, you can add a `README` file or `.gitignore` file there:
take a look at [this](http://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository).

**Comment by eggsactly** [comment]
@s1291 Pull Request #4 solves this issue by creating the output folder with the Makefile.

**Comment by dorchard** [comment]
Great! Merged!
